name: build_chat

on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: build and tests
      run: bash -c "sudo apt-get install -y make gcc && cd src && make all_noui"
